Ruby 1.9: fix tests error due to require path at test/test_helper.rb
Following error raises.

<pre>
/home/xxxxxx/.rvm/gems/ruby-1.9.2-p290/gems/rails-2.3.11/lib/rails/gem_dependency.rb:277:in `==':
   undefined method `name' for "actionmailer":String (NoMethodError)
...
	from /REDMINE-1/hg-workdir/redmine-bb-all/test/test_helper.rb:19:in `<top (required)>'
	from <internal:lib/rubygems/custom_require>:29:in `require'
	from <internal:lib/rubygems/custom_require>:29:in `require'
	from test/unit/changeset_test.rb:20:in `<main>'
</pre>

Moreover, in order to run tests on Ruby 1.9.2, Rails needs to be 2.3.14.